apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-reflector
  name: api-reflector
spec:
  selector:
    matchLabels:
      app: api-reflector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: app
      labels:
        app: api-reflector
    spec:
      containers:
      - image: ghcr.io/binkhq/api-reflector:latest
        name: app
        ports:
        - containerPort: 6502
        resources:
          limits:
            cpu: 250m
            memory: 256M
          requests:
            memory: 256M
